name: "Deploy no Chrome"
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          zip -r0 extension.zip src
      - name: Browser Plugin Publish
        uses: plasmo-corp/bpp@main
        with:
          artifact: "./extension.zip"
          keys: ${{ secrets.SUBMIT_KEYS }}
