name: "Deploy with Puppeteer"
on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        market: [OPERA_KEYS, EDGE_KEYS]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy ${{ matrix.market }}"
      - uses: actions/checkout@v2
      - name: Build
        run: sh build.sh
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: latest
      - name: Browser Plugin Publish
        uses: plasmo-corp/bpp@main
        env:
          PUPPETEER_EXECUTABLE_PATH: /opt/hostedtoolcache/chromium/latest/x64/chrome
        with:
          artifact: "./extension.zip"
          keys: ${{ secrets[matrix.market] }}
