name: "submit"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: 961656
      - name: Build
        run: sh build.sh
      - name: Browser Plugin Publish
        uses: plasmo-corp/bpp@v1
        with:
          artifact: "./extension.zip"
          keys: ${{ secrets.SUBMIT_KEYS }}
