name: "Deploy without Puppeteer"
on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        market: [CHROME_KEYS, FIREFOX_KEYS]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy ${{ matrix.market }}"
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd src
          zip -r ../extension.zip .
      - name: Browser Plugin Publish
        uses: PlasmoHQ/bpp@main
        with:
          artifact: "./extension.zip"
          keys: ${{ secrets[matrix.market] }}
